### ISSUE TITLE
use os_setCallback() instead of hacking timer

### ISSUE THREAD

**Issue by pierregremaud** [IoTDevicesCH/LoraMidiAtmega1284P#1]
This is not an issue, but more a proposition.

In ttn-otaa-sleepWDT.ino you use the following code (lines 262 .. 266)

            // LMIC uses micros() to keep track of the duty cycle, so
            // hack timer0_overflow for a rude adjustment:
            cli();
            timer0_overflow_count += 8 * 64 * clockCyclesPerMicrosecond();
            sei();

I would just delete them and change line 270 

        do_send(&sendjob);

to the following 👍 

          os_setCallback(&sendjob, do_send);

I have tried and it seems to work fine... So no need to hack the timer...

Regards 

Pierre Gremaud

**Comment by IoTDevicesCH** [comment]
Hello, thank you for the input. I tested this and yes, this looks like a better solution. I will update the examples soon!

**Comment by IoTDevicesCH** [comment]
I tested a bit further, only setting
`os_setCallback(&sendjob, do_send); `
will cause delay in the transmission, therefore power consumption is higher.

Better to use
```
timer0_overflow_count += 8 * 64 * clockCyclesPerMicrosecond();
os_setCallback(&sendjob, do_send);
```
The two lines
```
cli();
sei();
```
are not necessary, I will update the examples soon.
